### ISSUE TITLE
Finding a guide

### ISSUE THREAD

**Issue by jonreading81** [ampproject/wg-access-subscriptions#4]
We are looking to find a guide for the process of building a new extension, we would like to provide a new access_vendor for amp access to support our paywall service, please could you advise how to proceed? @jpettitt

**Comment by jonreading81** [comment]
I am waiting to get a response on how to find a guide as we would like to provide a new vendor component for amp-access. can you advise how to proceed @mrjoro

**Comment by mrjoro** [comment]
I think @jpettitt may be out of office right now; @chenshay do you know who can help with this?

/cc @ampproject/wg-access-subscriptions

**Comment by mrjoro** [comment]
I've asked around and it sounds like @jpettitt is the right person for this.  It looks like he'll be back by the end of next week.

Sorry for the delay in responding!

**Comment by jpettitt** [comment]
@jonreading81 apologies for the slow response. I'm the probably the best person to help.  Can you explain a bit about your proposed extension?  Any `amp-access` and not `amp-subscriptions`?

**Comment by jpettitt** [comment]
@jonreading81 are you still working on this?  If so please email me (same user name @google.com)

**Comment by jpettitt** [comment]
Closing as obsolete- feel free to re-open if you still need help
